name: 'Deploy Icecast 2'
on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: ./icecast.py
      

